"""
New database tables (Write from Module 1 perspective).
These store the output of the investigation agents.
"""

import datetime
import enum
from decimal import Decimal

from sqlalchemy import (
    Column, Integer, String, Text, Numeric, Boolean, DateTime,
    ForeignKey, Enum as SAEnum, JSON, Float,
)
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.mixins import IDMixin, TimestampMixin


# --------------- Enums ---------------

class EvidenceType(str, enum.Enum):
    TRANSACTION = "transaction"
    ORDER = "order"
    PAYMENT = "payment"
    REFUND = "refund"
    COMMUNICATION = "communication"
    CUSTOMER_INFO = "customer_info"
    MERCHANT_INFO = "merchant_info"
    UPLOADED_DOCUMENT = "uploaded_document"
    POLICY = "policy"
    OTHER = "other"


class EvidenceSource(str, enum.Enum):
    SYSTEM = "system"          # Auto-collected from database
    UPLOAD = "upload"          # Manually uploaded by investigator
    EXTERNAL_API = "external_api"  # Fetched from external service
    DERIVED = "derived"        # Generated by an agent


class EvidenceStatus(str, enum.Enum):
    COLLECTED = "collected"
    PROCESSING = "processing"
    VALIDATED = "validated"
    INVALID = "invalid"
    DUPLICATE = "duplicate"
    FLAGGED = "flagged"


class ValidationSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class ValidationCategory(str, enum.Enum):
    MISSING_EVIDENCE = "missing_evidence"
    CONTRADICTION = "contradiction"
    INCOMPLETE_SUBMISSION = "incomplete_submission"
    FORMAT_ISSUE = "format_issue"
    DUPLICATE_EVIDENCE = "duplicate_evidence"
    TIMELINE_GAP = "timeline_gap"
    POLICY_VIOLATION = "policy_violation"
    OTHER = "other"


class TimelineEventType(str, enum.Enum):
    TRANSACTION = "transaction"
    ORDER_PLACED = "order_placed"
    PAYMENT_MADE = "payment_made"
    REFUND_PROCESSED = "refund_processed"
    COMMUNICATION_SENT = "communication_sent"
    DISPUTE_FILED = "dispute_filed"
    EVIDENCE_UPLOADED = "evidence_uploaded"
    POLICY_APPLIED = "policy_applied"
    SYSTEM_EVENT = "system_event"
    OTHER = "other"


class PolicyMatchType(str, enum.Enum):
    EXACT = "exact"
    SEMANTIC = "semantic"
    KEYWORD = "keyword"
    CATEGORY = "category"


class CaseFileStatus(str, enum.Enum):
    DRAFT = "draft"
    COMPLETE = "complete"
    SUBMITTED = "submitted"
    ARCHIVED = "archived"


# --------------- Models ---------------

class CaseFile(Base, IDMixin, TimestampMixin):
    """
    The final structured output of Module 1.
    Contains the complete investigation package consumed by Module 2.
    """

    __tablename__ = "case_files"

    dispute_id = Column(Integer, ForeignKey("disputes.id"), nullable=False, index=True, unique=True)
    case_file_id = Column(String(100), unique=True, index=True, nullable=False, comment="Generated case file reference")
    status = Column(SAEnum(CaseFileStatus), nullable=False, default=CaseFileStatus.DRAFT)
    investigation_summary = Column(Text, nullable=True, comment="LLM-generated summary of the investigation")
    confidence_score = Column(Float, nullable=True, comment="Overall confidence score (0.0 to 1.0)")
    generated_by = Column(Integer, ForeignKey("users.id"), nullable=True, comment="User who generated the case file")
    submitted_at = Column(DateTime, nullable=True)
    metadata_json = Column(JSON, nullable=True)

    # Relationships
    dispute = relationship("Dispute")
    evidence_items = relationship("EvidenceRepository", back_populates="case_file")
    timeline_events = relationship("TimelineEvent", back_populates="case_file")
    validations = relationship("EvidenceValidation", back_populates="case_file")
    policy_mappings = relationship("PolicyMapping", back_populates="case_file")

    def __repr__(self) -> str:
        return f"<CaseFile(id={self.id}, case={self.case_file_id}, status={self.status})>"


class EvidenceRepository(Base, IDMixin, TimestampMixin):
    """
    Stores all collected evidence items for a dispute investigation.
    Each row represents a single piece of evidence.
    """

    __tablename__ = "evidence_repository"

    case_file_id = Column(Integer, ForeignKey("case_files.id"), nullable=False, index=True)
    evidence_id = Column(String(100), unique=True, index=True, nullable=False, comment="Generated evidence reference ID")
    evidence_type = Column(SAEnum(EvidenceType), nullable=False)
    source = Column(SAEnum(EvidenceSource), nullable=False, default=EvidenceSource.SYSTEM)
    status = Column(SAEnum(EvidenceStatus), nullable=False, default=EvidenceStatus.COLLECTED)

    # Source reference (which record in the existing tables does this come from?)
    source_table = Column(String(100), nullable=True, comment="e.g., transactions, orders, communications")
    source_record_id = Column(Integer, nullable=True, comment="Primary key of the source record")
    source_external_id = Column(String(100), nullable=True, comment="External ID from source system")

    # Content
    title = Column(String(500), nullable=True)
    description = Column(Text, nullable=True)
    content_text = Column(Text, nullable=True, comment="Extracted text content")
    content_json = Column(JSON, nullable=True, comment="Structured content data")
    file_url = Column(String(500), nullable=True, comment="URL to uploaded file if applicable")
    file_type = Column(String(50), nullable=True, comment="MIME type or file extension")
    file_size_bytes = Column(Integer, nullable=True)

    # Temporal
    event_date = Column(DateTime, nullable=True, index=True, comment="When the original event occurred")
    collected_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    # Entity references (extracted entities)
    merchant_name = Column(String(255), nullable=True)
    customer_name = Column(String(255), nullable=True)
    amount = Column(Numeric(12, 2), nullable=True)
    currency = Column(String(3), nullable=True)
    transaction_id_ref = Column(String(100), nullable=True)
    order_id_ref = Column(String(100), nullable=True)

    # Processing
    is_processed = Column(Boolean, default=False, nullable=False)
    processing_notes = Column(Text, nullable=True)
    metadata_json = Column(JSON, nullable=True)

    # Relationships
    case_file = relationship("CaseFile", back_populates="evidence_items")

    def __repr__(self) -> str:
        return f"<EvidenceRepository(id={self.id}, type={self.evidence_type}, status={self.status})>"


class TimelineEvent(Base, IDMixin, TimestampMixin):
    """
    Represents a single event in the chronological investigation timeline.
    """

    __tablename__ = "timeline_events"

    case_file_id = Column(Integer, ForeignKey("case_files.id"), nullable=False, index=True)
    event_id = Column(String(100), unique=True, index=True, nullable=False, comment="Generated event reference ID")
    event_type = Column(SAEnum(TimelineEventType), nullable=False)
    event_date = Column(DateTime, nullable=False, index=True)
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    sequence_order = Column(Integer, nullable=False, comment="Order in the timeline (1-based)")

    # Source evidence reference
    evidence_id = Column(Integer, ForeignKey("evidence_repository.id"), nullable=True, comment="Linked evidence item")
    source_table = Column(String(100), nullable=True)
    source_record_id = Column(Integer, nullable=True)

    # Details
    amount = Column(Numeric(12, 2), nullable=True)
    currency = Column(String(3), nullable=True)
    merchant_name = Column(String(255), nullable=True)
    customer_name = Column(String(255), nullable=True)
    metadata_json = Column(JSON, nullable=True)

    # Relationships
    case_file = relationship("CaseFile", back_populates="timeline_events")

    def __repr__(self) -> str:
        return f"<TimelineEvent(id={self.id}, type={self.event_type}, date={self.event_date})>"


class EvidenceValidation(Base, IDMixin, TimestampMixin):
    """
    Stores validation results for evidence completeness and quality.
    """

    __tablename__ = "evidence_validation"

    case_file_id = Column(Integer, ForeignKey("case_files.id"), nullable=False, index=True)
    validation_id = Column(String(100), unique=True, index=True, nullable=False, comment="Generated validation reference ID")
    category = Column(SAEnum(ValidationCategory), nullable=False)
    severity = Column(SAEnum(ValidationSeverity), nullable=False, default=ValidationSeverity.INFO)

    # What evidence is this about?
    evidence_id = Column(Integer, ForeignKey("evidence_repository.id"), nullable=True, comment="Related evidence item")
    evidence_type = Column(SAEnum(EvidenceType), nullable=True)

    # Validation details
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    detail = Column(Text, nullable=True, comment="Detailed explanation of the validation finding")
    suggestion = Column(Text, nullable=True, comment="Suggested action to resolve the issue")

    # For contradictions: which two pieces of evidence conflict?
    conflicting_evidence_id = Column(Integer, ForeignKey("evidence_repository.id"), nullable=True)
    conflicting_field = Column(String(100), nullable=True, comment="Which field has the contradiction")

    # Resolution
    is_resolved = Column(Boolean, default=False, nullable=False)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(String(100), nullable=True)
    resolution_notes = Column(Text, nullable=True)
    metadata_json = Column(JSON, nullable=True)

    # Relationships
    case_file = relationship("CaseFile", back_populates="validations")

    def __repr__(self) -> str:
        return f"<EvidenceValidation(id={self.id}, category={self.category}, severity={self.severity})>"


class PolicyMapping(Base, IDMixin, TimestampMixin):
    """
    Maps evidence and dispute details to applicable policies.
    """

    __tablename__ = "policy_mapping"

    case_file_id = Column(Integer, ForeignKey("case_files.id"), nullable=False, index=True)
    mapping_id = Column(String(100), unique=True, index=True, nullable=False, comment="Generated mapping reference ID")
    policy_id = Column(Integer, ForeignKey("policy_repository.id"), nullable=False, index=True)
    match_type = Column(SAEnum(PolicyMatchType), nullable=False, default=PolicyMatchType.KEYWORD)

    # What evidence triggered this policy match?
    evidence_id = Column(Integer, ForeignKey("evidence_repository.id"), nullable=True)
    evidence_type = Column(SAEnum(EvidenceType), nullable=True)

    # Match details
    relevance_score = Column(Float, nullable=True, comment="How relevant is this policy (0.0 to 1.0)")
    matched_text = Column(Text, nullable=True, comment="The specific text that matched")
    explanation = Column(Text, nullable=True, comment="Why this policy applies")
    is_applicable = Column(Boolean, default=True, nullable=False)

    # Historical similar disputes
    similar_dispute_id = Column(Integer, ForeignKey("disputes.id"), nullable=True)
    similarity_score = Column(Float, nullable=True, comment="Similarity to historical dispute (0.0 to 1.0)")
    metadata_json = Column(JSON, nullable=True)

    # Relationships
    case_file = relationship("CaseFile", back_populates="policy_mappings")
    policy = relationship("PolicyRepository")

    def __repr__(self) -> str:
        return f"<PolicyMapping(id={self.id}, policy={self.policy_id}, match={self.match_type})>"


class AuditLog(Base, IDMixin, TimestampMixin):
    """
    Central audit log for tracking all investigation actions.
    """

    __tablename__ = "audit_logs"

    action = Column(String(100), nullable=False, comment="e.g., evidence_collected, validation_created, case_generated")
    entity_type = Column(String(100), nullable=True, comment="e.g., evidence_repository, case_file, timeline_event")
    entity_id = Column(Integer, nullable=True, comment="ID of the affected record")
    dispute_id = Column(Integer, ForeignKey("disputes.id"), nullable=True, index=True)
    case_file_id = Column(Integer, ForeignKey("case_files.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, comment="Who performed the action")
    details = Column(Text, nullable=True, comment="Human-readable description")
    metadata_json = Column(JSON, nullable=True, comment="Structured details about the action")
    ip_address = Column(String(50), nullable=True)
    user_agent = Column(String(500), nullable=True)

    def __repr__(self) -> str:
        return f"<AuditLog(id={self.id}, action={self.action}, entity={self.entity_type})>"